layout_spectrum: 0
typography_spectrum: 0.4489362
color:
  saturation: 0
  lightness: 0.7319149
  brandStrength: 0.2081825
  rhythmicContrast: 0
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Jacinto Caetano Portfolio
